sudo: false
language: python
cache:
  directories:
  - $HOME/.cache/pip
install: pip install -U pip tox wheel
script: tox
notifications:
  email: false
env:
  - TOXENV=py27-django-18
  - TOXENV=py27-django-19
  - TOXENV=py27-django-110
  - TOXENV=py27-django-111
  - TOXENV=py34-django-18
  - TOXENV=py34-django-19
  - TOXENV=py34-django-110
  - TOXENV=py34-django-111
  - TOXENV=py35-django-18
  - TOXENV=py35-django-19
  - TOXENV=py35-django-110
  - TOXENV=py35-django-111
  - TOXENV=py36-django-18
  - TOXENV=py36-django-19
  - TOXENV=py36-django-110
  - TOXENV=py36-django-111
